services:
  - type: web
    name: sml-rails
    env: docker
    dockerfilePath: ./Dockerfile.rails
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: XRPL_NETWORK
        value: mainnet
      - key: XRPL_WS_MAINNET
        value: wss://xrplcluster.com
      - key: OPERATOR_WALLET_SEED
        sync: false
      - key: DISCORD_WEBHOOK_RAILS
        sync: false
      - key: RAILS_PORT
        value: "8002"
